// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    partial class BlogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Article", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("Content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Image");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit")
                        .HasColumnName("IsPublished");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("categoryId")
                        .HasColumnType("int")
                        .HasColumnName("categoryId");

                    b.Property<int>("userID")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("ID");

                    b.HasIndex("categoryId");

                    b.HasIndex("userID");

                    b.ToTable("Articles", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ArticleApproval", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("_adminId")
                        .HasColumnType("int");

                    b.Property<int>("_articleId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("_adminId");

                    b.HasIndex("_articleId")
                        .IsUnique();

                    b.ToTable("_articleApprovals");
                });

            modelBuilder.Entity("Domain.Entities.ArticleNotification", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("articleId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("articleId");

                    b.HasIndex("userId");

                    b.ToTable("_articleNotifications");
                });

            modelBuilder.Entity("Domain.Entities.ArticleQuestion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Ansewr")
                        .IsRequired()
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("Answer");

                    b.Property<DateTime>("AnsweredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("Question");

                    b.Property<int>("articleId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("articleId");

                    b.HasIndex("userId");

                    b.ToTable("ArticleQuestions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ArticleSummary", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("Summary");

                    b.Property<int>("articleId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("articleId")
                        .IsUnique();

                    b.ToTable("ArticleSummaries", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CategoryName");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Description");

                    b.HasKey("ID");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("articleID")
                        .HasColumnType("int")
                        .HasColumnName("articleId");

                    b.Property<int>("userID")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("ID");

                    b.HasIndex("articleID");

                    b.HasIndex("userID");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.GlobalChat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("_globalChat");

                    b.HasData(
                        new
                        {
                            ID = 2,
                            CreatedAt = new DateTime(2025, 12, 3, 11, 12, 58, 507, DateTimeKind.Local).AddTicks(72),
                            Description = "المحادثة المفتوحة لجميع المستخدمين",
                            Name = " GolbalChat For system"
                        });
                });

            modelBuilder.Entity("Domain.Entities.GlobalMessage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MessageType")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("senderId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("senderId");

                    b.ToTable("_golbalMessages");
                });

            modelBuilder.Entity("Domain.Entities.Like", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("articleId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("articleId");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("likes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Notification", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<string>("MessageNotification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("receiverId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IsRead");

                    b.HasIndex("MessageId");

                    b.HasIndex("receiverId");

                    b.ToTable("_notification");
                });

            modelBuilder.Entity("Domain.Entities.Persona", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("UserProfile", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Role");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Article", b =>
                {
                    b.HasOne("Domain.Entities.Category", "_category")
                        .WithMany("_articles")
                        .HasForeignKey("categoryId")
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "_user")
                        .WithMany("_articles")
                        .HasForeignKey("userID")
                        .IsRequired();

                    b.Navigation("_category");

                    b.Navigation("_user");
                });

            modelBuilder.Entity("Domain.Entities.ArticleApproval", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("_articleApprovals")
                        .HasForeignKey("_adminId")
                        .IsRequired();

                    b.HasOne("Domain.Entities.Article", "Article")
                        .WithOne("articleApproval")
                        .HasForeignKey("Domain.Entities.ArticleApproval", "_articleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.ArticleNotification", b =>
                {
                    b.HasOne("Domain.Entities.Article", "_article")
                        .WithMany("_articleNotifications")
                        .HasForeignKey("articleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "_user")
                        .WithMany("_articleNotifications")
                        .HasForeignKey("userId")
                        .IsRequired();

                    b.Navigation("_article");

                    b.Navigation("_user");
                });

            modelBuilder.Entity("Domain.Entities.ArticleQuestion", b =>
                {
                    b.HasOne("Domain.Entities.Article", "_article")
                        .WithMany("_articleQuestions")
                        .HasForeignKey("articleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "_user")
                        .WithMany("_articleQuestions")
                        .HasForeignKey("userId")
                        .IsRequired();

                    b.Navigation("_article");

                    b.Navigation("_user");
                });

            modelBuilder.Entity("Domain.Entities.ArticleSummary", b =>
                {
                    b.HasOne("Domain.Entities.Article", "_article")
                        .WithOne("articleSummary")
                        .HasForeignKey("Domain.Entities.ArticleSummary", "articleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_article");
                });

            modelBuilder.Entity("Domain.Entities.Comment", b =>
                {
                    b.HasOne("Domain.Entities.Article", "_article")
                        .WithMany("_comments")
                        .HasForeignKey("articleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "_user")
                        .WithMany("_comments")
                        .HasForeignKey("userID")
                        .IsRequired();

                    b.Navigation("_article");

                    b.Navigation("_user");
                });

            modelBuilder.Entity("Domain.Entities.GlobalMessage", b =>
                {
                    b.HasOne("Domain.Entities.User", "_user")
                        .WithMany("_Messages")
                        .HasForeignKey("senderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("_user");
                });

            modelBuilder.Entity("Domain.Entities.Like", b =>
                {
                    b.HasOne("Domain.Entities.Article", "_article")
                        .WithMany("_likes")
                        .HasForeignKey("articleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "_user")
                        .WithOne("_like")
                        .HasForeignKey("Domain.Entities.Like", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_article");

                    b.Navigation("_user");
                });

            modelBuilder.Entity("Domain.Entities.Notification", b =>
                {
                    b.HasOne("Domain.Entities.GlobalMessage", "_globalMessage")
                        .WithMany("_notifications")
                        .HasForeignKey("MessageId")
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "_receiver")
                        .WithMany("ReceivedNotifications")
                        .HasForeignKey("receiverId")
                        .IsRequired();

                    b.Navigation("_globalMessage");

                    b.Navigation("_receiver");
                });

            modelBuilder.Entity("Domain.Entities.Persona", b =>
                {
                    b.HasOne("Domain.Entities.User", "_user")
                        .WithOne("_userProfile")
                        .HasForeignKey("Domain.Entities.Persona", "userId")
                        .IsRequired();

                    b.Navigation("_user");
                });

            modelBuilder.Entity("Domain.Entities.Article", b =>
                {
                    b.Navigation("_articleNotifications");

                    b.Navigation("_articleQuestions");

                    b.Navigation("_comments");

                    b.Navigation("_likes");

                    b.Navigation("articleApproval");

                    b.Navigation("articleSummary");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("_articles");
                });

            modelBuilder.Entity("Domain.Entities.GlobalMessage", b =>
                {
                    b.Navigation("_notifications");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("ReceivedNotifications");

                    b.Navigation("_Messages");

                    b.Navigation("_articleApprovals");

                    b.Navigation("_articleNotifications");

                    b.Navigation("_articleQuestions");

                    b.Navigation("_articles");

                    b.Navigation("_comments");

                    b.Navigation("_like")
                        .IsRequired();

                    b.Navigation("_userProfile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
